services:
  - type: web
    name: llm-research-backend
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT genealogy_service:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: "*"
